# Generated by Django 3.2.20 on 2023-10-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRequestCache',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_id', models.CharField(max_length=128, unique=True, verbose_name='mqtt request')),
                ('status', models.CharField(choices=[('not_ready', 'Not Ready'), ('running', 'Running'), ('failed', 'Failed'), ('succeeded', 'Succeeded')], default='not_ready', max_length=10, verbose_name='request status')),
                ('url', models.CharField(max_length=512, null=True, verbose_name='mqtt request url')),
                ('method', models.CharField(choices=[('GET', 'Get'), ('POST', 'Post'), ('DELETE', 'Delete'), ('PUT', 'Put'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10, verbose_name='mqtt request method')),
                ('request_date', models.TimeField(verbose_name='request date')),
                ('result', models.CharField(max_length=1024, null=True, verbose_name='mqtt request result')),
                ('success', models.BooleanField(default=False)),
                ('error', models.CharField(max_length=512, null=True, verbose_name='mqtt request url')),
                ('response_date', models.TimeField(null=True, verbose_name='response date')),
            ],
            options={
                'verbose_name': 'mqtt_request',
                'verbose_name_plural': 'mqtt_requests',
            },
        ),
    ]
