# Generated by Django 3.2.20 on 2023-10-09 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationRequest',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True, verbose_name='migration id')),
                ('source_cluster_name', models.CharField(max_length=128, unique=True, verbose_name='source cluster name')),
                ('source_cluster_role', models.CharField(choices=[('Local', 'Local'), ('Remote', 'Remote'), ('None', 'None')], default='None', max_length=10, verbose_name='cluster role in multi-cluster')),
                ('delete_origin', models.BooleanField(default=False, verbose_name='delete origin pod')),
                ('source_namespace', models.CharField(max_length=128, null=True, verbose_name='source namespace')),
                ('source_pod', models.CharField(max_length=128, verbose_name='source pod')),
                ('target_cluster_name', models.CharField(max_length=128, unique=True, verbose_name='target cluster name')),
                ('target_node_name', models.CharField(max_length=128, unique=True, verbose_name='target node name')),
                ('status', models.CharField(default='ISSUED', max_length=32, verbose_name='migration status')),
                ('last_subtask_seq', models.IntegerField(default=0, verbose_name='current executing subtask sequence')),
                ('number_of_subtask', models.IntegerField(default=0, verbose_name='number of total subtask')),
                ('issued_date', models.TimeField(auto_now=True, verbose_name='issued date')),
                ('start_date', models.TimeField(null=True, verbose_name='start date')),
                ('end_date', models.TimeField(null=True, verbose_name='end date')),
                ('updated_date', models.TimeField(null=True, verbose_name='updated date')),
            ],
            options={
                'verbose_name': 'migration_request',
                'verbose_name_plural': 'migration_requests',
            },
        ),
        migrations.CreateModel(
            name='MigrationTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=128, verbose_name='task name')),
                ('status', models.CharField(default='ISSUED', max_length=32, verbose_name='task status')),
                ('error', models.CharField(default='NONE', max_length=32, verbose_name='migration error')),
                ('reason', models.CharField(max_length=512, null=True, verbose_name='error message')),
                ('retry', models.IntegerField(default=0, verbose_name='retry count')),
                ('sequence', models.IntegerField(default=0, verbose_name='task sequence number')),
                ('issued_date', models.TimeField(auto_now=True, verbose_name='issued date')),
                ('start_date', models.TimeField(null=True, verbose_name='start date')),
                ('end_date', models.TimeField(null=True, verbose_name='end date')),
                ('migration_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwlink_migration.migrationrequest')),
            ],
            options={
                'verbose_name': 'migration_task',
                'verbose_name_plural': 'migration_tasks',
            },
        ),
    ]
