# Generated by Django 3.2.20 on 2023-10-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwlink_migration', '0002_auto_20231016_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationtask',
            name='error',
            field=models.CharField(default='NONE', max_length=32, null=True, verbose_name='migration error'),
        ),
    ]
