# Generated by Django 3.2.20 on 2023-10-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwlink_migration', '0003_alter_migrationtask_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationrequest',
            name='target_node_name',
            field=models.CharField(max_length=128, verbose_name='target node name'),
        ),
    ]
