# Generated by Django 3.2.20 on 2023-10-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwlink_migration', '0004_alter_migrationrequest_target_node_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationrequest',
            name='source_cluster_name',
            field=models.CharField(max_length=128, verbose_name='source cluster name'),
        ),
        migrations.AlterField(
            model_name='migrationrequest',
            name='target_cluster_name',
            field=models.CharField(max_length=128, verbose_name='target cluster name'),
        ),
    ]
