# Generated by Django 3.2.20 on 2023-10-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cluster_id', models.CharField(max_length=128, unique=True, verbose_name='cluster id')),
                ('cluster_name', models.CharField(max_length=128, unique=True, verbose_name='cluster name')),
                ('description', models.CharField(max_length=512, null=True, verbose_name='cluster description')),
                ('registration_command', models.CharField(max_length=2048, null=True, verbose_name='agent registration command')),
                ('mc_connect_id', models.CharField(default=None, max_length=128, null=True, verbose_name='multicluster connection id')),
                ('role', models.CharField(choices=[('Local', 'Local'), ('Remote', 'Remote'), ('None', 'None')], default='None', max_length=10, verbose_name='cluster role in multi-cluster')),
                ('mc_config_state', models.CharField(choices=[('Connecting', 'Connecting'), ('Connected', 'Connected'), ('DisconnectPending', 'Disconnect Pending'), ('Disconnecting', 'Disconnecting'), ('None', 'None')], default='None', max_length=20, verbose_name='multi-cluster config state')),
                ('broker_info', models.CharField(max_length=2048, null=True, verbose_name='broker info file')),
                ('broker_info_update_date', models.TimeField(null=True, verbose_name='broker-info.subm update date')),
                ('create_date', models.TimeField(auto_now=True, verbose_name='create date')),
                ('update_date', models.TimeField(auto_now=True, verbose_name='update date')),
            ],
            options={
                'verbose_name': 'cluster',
                'verbose_name_plural': 'clusters',
            },
        ),
    ]
